name: Build package

env:
  zip-link: https://cdn.discordapp.com/attachments/811651707599192096/1061327961636216932/repo.zip

on:
  release:
    types: [published]

  workflow_dispatch:
      
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
    
      - name: Install dependencies
        run: poetry install
      
      - name: Build and install projet
        run: poetry build && pip install dist/pydeb*.whl
        
      - name: Get repo zip
        run: |
            wget ${{ env.zip-link }}
            unzip repo.zip
    
      - name: Attempt to extract deb
        run: python tests/test.py